In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [4]:
arr = np.array([1,2,3,4])
x =arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4]
[31  2  3  4]
