In [1]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [2]:
arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [7]:
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
