In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [2]:
print(arr[4:])

[5 6 7]


In [3]:
print(arr[:4])

[1 2 3 4]


In [4]:
print(arr[-3:-1])

[5 6]


In [6]:
print(arr[::2])
print(arr[1:5:2])

[1 3 5 7]
[2 4]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [10]:
print(arr[0:2, 2])
print(arr[:, 2])

[3 8]
[3 8]


In [11]:
print(arr[:, 1:4])

[[2 3 4]
 [7 8 9]]


In [16]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print(arr)
print(arr[::2, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  3]
 [ 9 11]]
