In [2]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr.dtype)

int64


In [4]:
arr = np.array(["apple", "bnana", "cherry"])

print(arr.dtype)

<U6


In [3]:
arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1,2,3,4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [15]:
# exception
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [17]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(f"arr: {arr}")
print(f"arr type: {arr.dtype}")
print(f"newarr: {newarr}")
print(f"newarr type: {newarr.dtype}")

arr: [1.1 2.1 3.1]
arr type: float64
newarr: [1 2 3]
newarr type: int32


In [18]:
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
arr = np.array([1,0,3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[1 0 3]
int8


In [21]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]
