In [3]:
import numpy as np

arr = np.array([1.1, 3.3, 5.5, 7.7, 0.0])

intarr = arr.astype('i')
boolarr = arr.astype(bool)

arrays = [arr, intarr, boolarr]

for array in arrays:
    print(array)
    print(array.dtype)

[1.1 3.3 5.5 7.7 0. ]
float64
[1 3 5 7 0]
int32
[ True  True  True  True False]
bool


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
a = "12345"
b = a

a = "qwerty"

print(a)
print(b)

qwerty
12345
